version: "3"
services:
  app:
    container_name: work-container
    build: .
#    image: wardkey/springapp:5901b36d99c2d0f63d6dae300bbb1ea99526dcea
    depends_on:
      - database
    ports:
      - "8972:8888"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://database:3306/encore?useUnicode=true
      SPRING_DATASOURCE_USERNAME: work_user
      SPRING_DATASOURCE_PASSWORD: work_passwd
    restart: always
    links:
      - database
    # platform: linux/arm64
  database:
    image: mariadb:10.6.16
    container_name: workdb-container
    environment:
      MARIADB_ROOT_PASSWORD: 1234
      MARIADB_USER: work_user
      MARIADB_PASSWORD: work_passwd
      MARIADB_DATABASE: encore
    volumes:
      - ./src/main/resources/db_config/initdb:/docker-entrypoint-initdb
    ports:
      - "6033:3306"