
# 워크플로우의 이름
name: java with Gradle

# 트리거 설정
on:
  push:
    branches: [main]

jobs:
  build:
    # runner를 설치
    runs-on: ubuntu-latest

    #소스코드 체크아웃
    steps:
      - name: Source Checkout
        uses: actions/checkout@v2

      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
