
# 워크플로우의 이름
name: java with Gradle

# 트리거 설정
on:
  push:
    branches: [main]

jobs:
  build:
    # runner를 설치
    runs-on: ubuntu-latest

    #소스코드 체크아웃
    steps:
      - name: Source Checkout
        uses: actions/checkout@v2

      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      # jar file build and permission
      - name: Grant jar
        run: chmod +x gradlew

      - name: Build Jar
        run: ./gradlew build bootJAR

      # runner(ubuntu) docker buildx install(도커 이미지를 빌드하기 위해서는 docker buildx 설치 필요)
      - name: Docker buildx
        uses: docker/setup-buildx-action@v2
      # docker image build to push docker hub



